### PR TITLE
Removed web map from Open map URL sample

### PR DESCRIPTION
**Pull request by duffh**
# Description

Removed a web map from the Open map URL sample as this web map is no longer active. 

## Type of change

- Other enhancement

## Platforms tested on

- [x] WPF .NET 6
- [ ] WPF Framework
- [x] WinUI
- [x] MAUI WinUI
- [ ] MAUI Android
- [ ] MAUI iOS
- [ ] MAUI MacCatalyst

## Checklist

- [x] Self-review of changes
- [ ] All changes work as expected on all affected platforms
- [x] There are no warnings related to changes
- [x] Code is commented and follows .NET conventions and standards
- [x] Codemaid and XAML styler extensions have been run on every changed file
- [x] No unrelated changes have been made to any other code or project files

### CODE REVIEW

**Comment by duffh** [comment]
The check that is failing is a result of the URL not being wrapped in `< >` braces. This is not a standard we have been following in our other readme files so I will merge with the check failing once this has been approved.

**Comment by duffh** [comment]
The check that is failing is a result of the URL not being wrapped in `< >` braces. This is not a standard we have been following in our other readme files so I will merge with the check failing once this has been approved.

**Review by williambohrmann3 — APPROVED** [review]
Do we need to update MD034 (markdown rule) to allow this type of link in our readme's? This format with the [name](link) used in other samples (i.e. Query Feature Count and Extent) so it probably shouldn't be flagging it.

**Review by amweis226 — APPROVED** [review]

**Comment by duffh** [comment]
> Do we need to update MD034 (markdown rule) to allow this type of link in our readme's? This format with the `[name](link)` is used in other samples (i.e. Query Feature Count and Extent) so it probably shouldn't be flagging it as an unsuccessful check.

I think the best approach is to remove it, I'll see if I can find out why it's not been an issue until just now.

**Pull request merged**
