### PR TITLE
Updated copyright year to 2023 in all files

### PR DESCRIPTION
**Pull request by pMaske**
# Description
Updated copyright year to 2023 in all files

Summary of the change and any relevant info.

## Type of change

- Bug fix
- New sample implementation
- Sample viewer enhancement
- Other enhancement

## Platforms tested on

- [ ] WPF .NET 6
- [ ] WPF Framework
- [ ] WinUI
- [ ] MAUI WinUI
- [ ] MAUI Android
- [ ] MAUI iOS
- [ ] MAUI MacCatalyst

## Checklist

- [ ] Self-review of changes
- [ ] All changes work as expected on all affected platforms
- [ ] There are no warnings related to changes
- [ ] Code is commented and follows .NET conventions and standards
- [ ] Codemaid and XAML styler extensions have been run on every changed file
- [ ] No unrelated changes have been made to any other code or project files
- [ ] Screenshots are correct size and display in description tab (800 x 600 on Windows, 600 height mobile screenshots for MAUI)

### CODE REVIEW

**Comment by ZackAllen** [comment]
Do we need to change all older years to 2023 as well? I only see 2022 MAUI changes and one shared file. There are still plenty of 2016-2021 files in the repo.

**Comment by pMaske** [comment]
@ZackAllen I am not sure either. I will check with sample design council to see what other SDKs do.

**Review by duffh — APPROVED** [review]

**Comment by pMaske** [comment]
Based on https://devtopia.esri.com/runtime/dotnet-api/wiki/.NET-Samples-conventions-and-standards#copyright-years I don't this we need to update all files. @duffh can you please confirm ?

**Comment by duffh** [comment]
> Based on https://devtopia.esri.com/runtime/dotnet-api/wiki/.NET-Samples-conventions-and-standards#copyright-years I don't this we need to update all files. @duffh can you please confirm ?

You are right, let's not merge this change. I'll update the sample template year to 2023 in line with this convention.

**Pull request closed without merging**
